version: '2'
services:
   bitcoin:
      build:
         context: ./build/docker-bitcoin-qt
         dockerfile: Dockerfile
         args:
            username: "bitcoin"
      image: bitcoin:latest
      ports:
         - "8333:8333"
      volumes:
         - "./run/datadir:/home/${username}/datadir"
